---

- name: Apache installation

  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: package setup
      yum:
        name: httpd
        state: present
    - name: service enabling
      service:
        name: httpd
        enabled: yes
        state: started
    - name: copy welcome page
      copy:
        content: "Welcome to my web server"
        dest: /var/www/html/index.html
        owner: apache
        mode: 0644
    - name: open ports
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      notify: restart firewalld
      loop:
        - http
        - https

  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted
